services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWUSER_ID: ${WWWUSER_ID:-1000}
                WWWGROUP_ID: ${WWWGROUP_ID:-1000}
        ports:
            - '${FORWARD_APP_PORT:-8000}:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        tty: true
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - '../:/app'
            - 'sail-profile:/home/sail:cached'
            - '/home/sail/.vscode-server'
        networks:
            - sail
        depends_on:
            - db
            - redis
            - mailpit

    db:
        image: 'mysql:9'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        command: ["--max-allowed-packet=1073741824", "--sort-buffer-size=1073741824"]
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:7-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-profile:
