name: Run Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/tests.yml'
      - 'composer.json'
      - 'composer.lock'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]
        laravel: [12.*]
        stability: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 9.*
            carbon: ^2.63

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    services:
      db-testing:
        image: mysql:9
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: 'testing'
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Verify testing DB exists
        run: mysql --host 127.0.0.1 --port 33306 -uroot -ptesting -e "SHOW DATABASES LIKE 'testing'"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 33306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: testing
        run: ./vendor/bin/pest --ci
